<a href="https://colab.research.google.com/github/mayconmcardoso/Data-Science-Studies/blob/main/Working_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green>NUMPY
---

# <font color=green> 1. INTRODUCTION TO PYTHON
---

# 1.1 Numpy Arrays

In [1]:
import numpy as np

In [4]:
km = np.loadtxt('carros-km.txt')

In [5]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [11]:
years = np.loadtxt('carros-anos.txt', dtype = int)

In [12]:
years

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Getting the average kilometers per year




In [14]:
km_average = km / (2019 - years)

#we got an error because there are some divisions with 0 when it happens python changes to nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [15]:
km_average

array([2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
       1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
       1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02,
       4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
       6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
       5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03,
                  nan,            nan, 1.93166667e+03,            nan,
       3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
       1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03,
                  nan,            nan, 5.52600000e+02,            nan,
       1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                  nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02,
                  nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
       3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24028000e+03,
      

In [16]:
type(km_average)

numpy.ndarray

## 1.2 Math operations

### Arithmetic operators : $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Addition ($+$)

In [ ]:
2 + 2

4

### Subtraction ($-$)

In [ ]:
2 - 2

0

### Multiplication ($*$)

In [ ]:
2 * 3

6

### Division ($/$) and ($//$)
The division operation always returns a floating point number

In [ ]:
10 / 3

3.3333333333333335

In [17]:
10 // 3

3

### Exponenciação ($**$)

In [18]:
2 ** 3

8

### Division remainder ($\%$)

In [19]:
10 % 3

1

In [20]:
10 % 2

0

### Math expressions

In [21]:
5 * 2 + 3 * 2

16

In [22]:
(5 * 2) + (3 * 2)

16

In [23]:
5 * (2 + 3) * 2

50

### Variable _

In interactive mode, the last printed result is assigned to the variable _

In [24]:
5 * 2

10

In [25]:
_ + 3 * 2

16

In [26]:
_ / 2

8.0

# 1.3 Type conversion



In [27]:
a = 10
b = 20
c = 'Python is '
d = 'cool'

In [28]:
type(a)

int

In [29]:
type(b)

int

In [30]:
type(c)

str

In [31]:
type(d)

str

In [32]:
a + b

30

In [33]:
c + d

'Python is cool'

### type conversion

Functions int(), float(), str()

In [36]:
str(a)

'10'

In [37]:
type(str(a))

str

In [38]:
c + str(a)

'Python is 10'

In [39]:
float(a)

10.0

In [40]:
var = 3.141592

In [41]:
int(var)

3

In [42]:
var = 3.99

In [43]:
int(var)

3

# <font color=green> 2. Working with lists
---

# 2.1 Lists operations

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Print **True** if an element of list A is equal to x.

In [44]:
Accessories = ['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [45]:
'Rodas de liga' in Accessories

True

In [46]:
'4 X 4' in Accessories

False

In [47]:
'Rodas de liga' not in Accessories

False

In [48]:
'4 X 4' not in Accessories

True

## *A + B*

Concatenate the lists **A** and **B**.

In [49]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [50]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [51]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [52]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

'A' list length

In [53]:
len(Accessories)

8

# 2.2 List methods

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

In [54]:
Accessories = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

## *A.sort()*


In [55]:
Accessories

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [56]:
Accessories.sort()
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*


In [57]:
Accessories.append('4 X 4')
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

## *A.pop(i)*

Removes and prints index element i from list *A*.
By default it removes and prints the last element

In [58]:
Accessories.pop()

'4 X 4'

In [59]:
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [60]:
Accessories.pop(3)

'Rodas de liga'

In [61]:
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Create a copy of list A

<font color=red>**Observação:**</font> The same result can be obtained with the following code:
```
A[:]
```

In [62]:
Accessories_2 = Accessories
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [63]:
Accessories_2.append('4 X 4')
Accessories_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [64]:
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [65]:
Accessories.pop()
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [66]:
Accessories_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [67]:
Accessories_2 = Accessories.copy()
Accessories_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [68]:
Accessories_2.append('4 X 4')
Accessories_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [69]:
Accessories

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [70]:
Accessories_2 = Accessories[:]
Accessories_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# <font color=green> 

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [ ]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# <font color=green> 3. Basic Numpy
---

# 3.1 Creating Numpy Arrays

In [71]:
import numpy as np

### By lists

https://numpy.org/doc/1.16/user/basics.creation.html

In [72]:
km = np.array([1000, 2300, 4987, 1500])

In [73]:
km

array([1000, 2300, 4987, 1500])

In [74]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [75]:
km.dtype

dtype('int64')

### By external data

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [76]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)

In [77]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [78]:
km.dtype

dtype('int64')

### Two-dimensional arrays

In [80]:
datas = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
datas

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [82]:
Acessorios = np.array(datas)

In [83]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [84]:
km.shape

(258,)

In [85]:
Acessorios.shape

(3, 8)

### Comparing lists performance

In [86]:
np_array = np.arange(1000000)

In [87]:
py_list = list(range(1000000))

In [88]:
%time for _ in range(100): np_array *= 2

CPU times: user 64.4 ms, sys: 570 µs, total: 65 ms
Wall time: 67.4 ms


In [89]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.26 s, sys: 2.44 s, total: 11.7 s
Wall time: 11.7 s


# 3.2 numpy array math operations

In [90]:
km = [44410., 5712., 37123., 0., 25757.]
years = [2003, 1991, 1990, 2019, 2006]

In [92]:
idade = 2019 - years

TypeError: ignored

In [93]:
km = np.array([44410., 5712., 37123., 0., 25757.])
years = np.array([2003, 1991, 1990, 2019, 2006])

In [95]:
ages = 2019 - years

In [96]:
ages

array([16, 28, 29,  0, 13])

### Arrays operations

In [98]:
km_average = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [99]:
km_average

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [100]:
44410 / (2019 - 2003)

2775.625

In [101]:
5712 / (2019 - 1991)

204.0

### Two-dimensional arrays operations

In [102]:
dados = np.array([km, years])

In [103]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [104]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [105]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [106]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [107]:
km_average = dados[0] / (2019 - dados[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [108]:
km_average

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# 3.3 Numpy arrays attributes and methods

In [ ]:
dados = np.array([[44410., 5712., 37123., 0., 25757.],
                  [2003, 1991, 1990, 2019, 2006]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### Attributes

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

## *ndarray.shape*

Prints a tuple with the dimensions of the array.

In [109]:
dados.shape

(2, 5)

## *ndarray.ndim*

Prints the number of dimensions in the array.

In [110]:
dados.ndim

2

## *ndarray.size*

Prints the number of elements in the array.

In [111]:
dados.size

10

## *ndarray.dtype*

Prints the data type of array elements.

In [112]:
dados.dtype

dtype('float64')

## *ndarray.T*

Prints the transposed array, that is, converting rows to columns and vice versa.

In [113]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [114]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Methods

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Prints the array as a Python list.

In [115]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Prints an array that contains the same data in a new form.

In [116]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [118]:
contador.reshape((5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [119]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [121]:
km = [44410, 5712, 37123, 0, 25757]
years = [2003, 1991, 1990, 2019, 2006]

In [122]:
info_cars = km + years
info_cars

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [123]:
np.array(info_cars).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [124]:
np.array(info_cars).reshape((5, 2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Change the shape and size of the array.

In [125]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [126]:
dados_new.resize((3, 5), refcheck=False)

In [127]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [128]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [129]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# 5.5 Statistics

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

and

https://numpy.org/doc/1.16/reference/routines.statistics.html

and

https://numpy.org/doc/1.16/reference/routines.math.html

In [131]:
years = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
value = np.loadtxt(fname = "carros-valor.txt")

In [132]:
years.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [133]:
dataset = np.column_stack((years, km, value))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [134]:
dataset.shape

(258, 3)

## *np.mean()*

Prints the average of array elements along the specified axis.

In [135]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [136]:
np.mean(dataset, axis = 1)

array([44830.54666667, 37954.98      , 37315.05333333, 42189.35666667,
       40125.03333333, 36745.91      , 19488.06666667, 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18400.79333333, 56984.80666667, 59177.8       ,
       36526.53      , 30190.46333333, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.46666667, 77867.61333333, 76878.21666667,
       41205.07      , 24462.03333333, 34386.25      , 35817.28      ,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.19666667, 41766.95666667, 25768.39333333, 34876.18      ,
       54475.06333333, 59333.43      , 29553.44666667, 75040.79666667,
       39881.91      , 22655.23333333, 52057.21666667, 31725.88333333,
       22240.03333333, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [137]:
np.mean(dataset[:, 1])

44499.41472868217

In [138]:
np.mean(dataset[:, 2])

98960.51310077519

## *np.std()*

Prints the standard deviation of array elements along the specified axis.

In [139]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Prints the sum of array elements along the specified axis.

In [140]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [141]:
dataset[:, 1].sum()

11480849.0

## *np.sum()*


In [142]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [143]:
np.sum(dataset[:, 2])

25531812.38